version: '3.8'

services:
  # ========================================
  # Nginx Reverse Proxy
  # ========================================
  nginx:
    image: nginx:alpine
    container_name: ripy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - ripy-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # Token Server Application
  # ========================================
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ripy-token-server
    restart: unless-stopped
    env_file:
      - ./app/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/logs:/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - ripy-network
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # MariaDB Database
  # ========================================
  mariadb:
    image: mariadb:10.11
    container_name: ripy-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-ripy_root_pass}
      MYSQL_DATABASE: ${DB_NAME:-ripy_token}
      MYSQL_USER: ${DB_USER:-ripy_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ripy_pass}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      - ripy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-ripy_root_pass}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "3306"

networks:
  ripy-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local